### ISSUE TITLE
NMRs if a country is in CD.

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#101]
On vDip we do count the phases played and missed, even if a country is in CD.
That way, as long as your country is in CD it's rating get's a hit each phase.

You could leave your country 4 phases in CD and receive only 2 NMRs (or even less) if it would stop counting after a CD.

**Comment by TimothyJones** [comment]
This seems like a reasonable change - it would also naturally punish players more for CDing in bad positions.

It's also a one line change. I'll do it next time I have time.

**Comment by Sleepcap** [comment]
It might be a good idea to count up the phases-played counter too (Like you do with players NMR).
So a CD-NMR does count like phasesplayed+1 and NMR+1.
Some players with early CDs might have more NMRs as phases played. Also the statistic would be different if you count "normal" NMRs different from CD-NMRs.

**Comment by TimothyJones** [comment]
Good catch. That's an important bug - if we don't count them as phases played, then it's possible for the RR to go haywire.

**Comment by Sleepcap** [comment]
Mayer just add the SQL change to the 2nd one too...
