### ISSUE TITLE
Preview bug: fleets on specific coasts do not go away after being disbanded

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#106]
From a member:

>note the fleet at STP(sc) before and after preview mode
http://webdiplomacy.net/board.php?gameID=155311
Autumn 08
http://puu.sh/g0xZN/f5e7b0e6a6.jpg
http://puu.sh/g0y0D/1a48c86383.jpg

**Comment by Sleepcap** [comment]
In map.php (line 402) you didn't use the "deCoast"-function.
if (PREVIEW && in_array($Game->Variant->deCoast($drawToTerrID), $destroyedTerrs)) continue;
