### ISSUE TITLE
Disappearing pre-game join button

### ISSUE THREAD

**Issue by 2ndWhiteLine** [kestasjk/webDiplomacy#110]
Join button disappears occasionally before a game is full.  I believe this happens when the possible seventh player joins at the same time another player leaves.

**Comment by TimothyJones** [comment]
If the last player leaves a game before it has started (eg a live game), then the minimum bet is not correctly reset.

**Comment by TimothyJones** [comment]
This can be fixed with a call to `resetMinimumBet()` when a player leaves a starting game.

**Comment by jmo1121109** [comment]
Fixed
