### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by kestasjk** [kestasjk/webDiplomacy#111]
Perhaps we should include a default privacy policy which details what info is stored about users and why? (We might need to add some default clearing systems to enforce the defaults)

**Comment by Sleepcap** [comment]
At least in europe such a warning is needed by law.
That's why every site has one if you view the site from an european IP.

**Comment by jmo1121109** [comment]
This should be moved to an email discussion. Having this discussion here will violate the mod rules of not disclosing information that could compromise how mods find cheaters. I'd honestly prefer this issue be deleted once the conversation is moved.

**Comment by kestasjk** [comment]
Fair point, can't remove the issue but we can discuss the specifics offline. Interested if people beyond the official site think there should be a default policy or if it should be left completely up to each site.
