### ISSUE TITLE
Live games could have a set time after which they'll change phase length

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#114]
Currently live games are an unknown time commitment  -they can go anywhere between 2 and 5 hours. It would be more predictable for users if live games were able to be set to "live for the first 2 hours, and then <X> phase length afterwards".

This change has three configurable parts:
- Initial phase length (eg 5 minutes)
- Time for the initial phase length to run for (eg 3 hours)
- Phase length to change to once the initial period is up (eg 48 hours)

**Comment by jmo1121109** [comment]
this was implemented.
