### ISSUE TITLE
Forum searchable...

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#117]
In looking for a suitable thread in the forum to post about this in, it occurred to me that it might be a good idea to make the forum searchable.

**Comment by TimothyJones** [comment]
I agree. The webdip mod team have also raised the possibility of integrating a third party forum instead of the existing forum - this would allow for multiple topic boards, and a whole host of other features.

**Comment by TimothyJones** [comment]
With the new forum, this is no longer necessary.
