### ISSUE TITLE
Disbanded fleet still present on preview map.

### ISSUE THREAD

**Issue by CaptainMeme** [kestasjk/webDiplomacy#122]
![map1](https://cloud.githubusercontent.com/assets/10822890/7124819/eaf5579a-e223-11e4-9091-652ba3fb8ba1.png)
![map2](https://cloud.githubusercontent.com/assets/10822890/7124829/f5914b96-e223-11e4-8f01-dada7e41a00c.png)

The fleet in StP (sc) was disbanded, so should not appear in the preview map, but appears anyway.

**Comment by TimothyJones** [comment]
Thanks Capt! This is actually the same as #106
