### ISSUE TITLE
TD powers should allow users to post in global

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#127]
Currently, Tournament Director powers do not allow users to post in global (as moderators are able to). It would be an improvement to allow users with TD powers over a game to be able to post in the global chat for the game.

**Comment by jmo1121109** [comment]
This would have to only work for TD's who are not in the game.

**Comment by jmo1121109** [comment]
Fixed by https://github.com/kestasjk/webDiplomacy/pull/312
