### ISSUE TITLE
Cancel games with first turn NMRs

### ISSUE THREAD

**Issue by 2ndWhiteLine** [kestasjk/webDiplomacy#133]
Cancel live games with an NMR in the first turn.

**Comment by TimothyJones** [comment]
This is related to #113 - if we did that, then I don't think we'd need to cancel games with a first turn NMR.

I'm also interested in vDip's NMR policy - or in auto-extending the game phase if there's a first turn NMR. I think cancelling the game punishes the other 6 players who waited on the game to start - it'd be good to come up with a way of filling the NMR spots without progressing the phase.

**Comment by TimothyJones** [comment]
I think that #143 means that this isn't necessary any more - especially as cancelling automatically reduces members ability to follow what happened and why.
