### ISSUE TITLE
Change press type when WFO is waiting

### ISSUE THREAD

**Issue by 2ndWhiteLine** [kestasjk/webDiplomacy#135]
When a game goes into WFO mode, press type should change to "no press" so players aren't able to abuse the feature to gain extra press time.

**Comment by TimothyJones** [comment]
This would be a good improvement. It should probably change the game to public press, so that users can still discuss the waiting time and contacting moderators.

Additionally, the press box could be replaced with a useful message like "No private press while waiting for orders".

**Comment by TimothyJones** [comment]
Ideally, the press boxes are still available (so that old press can be read); users just can't send any new press.

**Comment by jmo1121109** [comment]
This is no longer needed.
