### ISSUE TITLE
Phase should auto extend to a full phase length when a takeover happens

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#144]
If a game is in Diplomacy, Builds or Retreats and a CDed player is replaced, the phase should auto extend to the full phase length to give them a fair shot at press/considering their moves.

**Comment by jmo1121109** [comment]
You just probably want to make sure that this does not happen for someone who retakes over a position they let go into CD themselves.

**Comment by jmo1121109** [comment]
With the new nmr system this isn't needed.
