### ISSUE TITLE
Replies Memory Error

### ISSUE THREAD

**Issue by CaptainMeme** [kestasjk/webDiplomacy#146]
For some users with a lot of posts, the replies link on the userpage gives an error message:

Fatal error: Allowed memory size of 8388608 bytes exhausted (tried to allocate 3096916 bytes) in /usr/local/www/apache24/data/webdiplomacy/profile.php on line 225

This example is taken from the following page:
http://webdiplomacy.net/profile.php?detail=replies&userID=4946

**Comment by TimothyJones** [comment]
Issue #147 would make this issue go away.

**Comment by TimothyJones** [comment]
No longer relevant now that there's a new forum.
