### ISSUE TITLE
Consider replacing the forum

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#147]
Many forum features are missing or broken (eg #117, #146, #93 and #148). If we replaced the forum with an integrated solution like http://vanillaforums.org/ , then we'd fix these issues, and get a number of other improvements for free (ability to create links, format posts, have multiple forum categories).

Any solution here would need to integrate with our login system so that users have a single sign in.

**Comment by yewang** [comment]
[Discourse](https://github.com/discourse/discourse) might be a nice solution, however, I'm not sure how easy/hard it would be to integrate with the WebDip login system.

**Comment by TimothyJones** [comment]
I have half an implementation integrating Vanilla Forums- I can share the branch if you're interested

**Comment by TimothyJones** [comment]
Considered, and done by @kestasjk !
