### ISSUE TITLE
Refreshing the page resends last message

### ISSUE THREAD

**Issue by cmhhss1** [kestasjk/webDiplomacy#154]
If you send a message and then refresh the page (in Chrome) it resends the last message.

![image](https://cloud.githubusercontent.com/assets/5523521/7778271/5e3d2a96-008f-11e5-93ae-bddf4a368b4e.png)

**Comment by TimothyJones** [comment]
This is a known issue, but we really should fix it. Issue #44 and #60 are related, but not the same.

**Comment by sp4cecat** [comment]
Pretty straightforward; redirect after submission (for any form submission) I might fork off and have a look tomorrow :)

**Comment by TimothyJones** [comment]
That would be great! There's a `redirect.php`, which you can extend to keep all the redirects consistent. Let us know if you have any questions.

**Comment by cfhughes** [comment]
I've submitted a pull request, #329, which submits messages in the background, and will solve this

**Comment by jmo1121109** [comment]
Fixed as mentioned by @cfhughes, thanks for that!
