### ISSUE TITLE
Remove or move defeated games in the My Games widget

### ISSUE THREAD

**Issue by yewang** [kestasjk/webDiplomacy#157]
Currently, games where a user has already been defeated still appear in the "My Games" widget on the home page until the game has finished.

Perhaps, one of these alternatives could be considered:
1) Remove such games from the "My Games" list
2) Move them to the "Spectated Games" list
3) Move them to a new list called something like "Defeated Games" or "Wall of Shame"

**Comment by TimothyJones** [comment]
This is related (but different) to #103.

I like option 2, but it has a few edge cases. I think it would require a slight rewrite of the spectator code (which doesn't show any spectated game that you're also a member of). 

If you wanted to make a pull request with this feature, I'd absolutely accept it.

**Comment by jmo1121109** [comment]
Done, went with option 3.
