### ISSUE TITLE
Accept username or email for Reset Password

### ISSUE THREAD

**Issue by newbyca** [kestasjk/webDiplomacy#158]
Hi, I can't remember my username or password. I still use the same email address I registered with but Reset Password only accepts username. 
- I tried searching my inbox, but can't find any emails with my username.

**Comment by TimothyJones** [comment]
This is a good change.

Note that the profile search at http://webdiplomacy.net/profile.php accepts email addresses, so as a work around, you can find your username that way. Or you can email the moderators at webdipmod@gmail.com

**Comment by newbyca** [comment]
Thanks @TimothyJones ...fyi, looks like you have to be logged in to get results from profile.php. I asked some other players to look it up for me though, so no problem.

**Comment by TimothyJones** [comment]
Ah, something else we should change. I've created #159 to allow users who aren't logged in to search.

**Comment by jmo1121109** [comment]
I've updated the password reset page with a lot more detail so this is no longer needed.
