### ISSUE TITLE
Allow guest users to use the search feature at profile.php

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#159]
For some reason, only logged in members are able to use the profile search.

We should change this so that everyone can use the profile search.

**Comment by jmo1121109** [comment]
I disagree with this. As it would open the door for bots to simply increment the userID search, and pull all emails that aren't hidden. I think this would also open us up to performance based attacks by having thousands of search requests at once.

**Comment by marknsikora** [comment]
@jmo1121109  if you're posting your email anywhere online you should assume it is going to be harvested

**Comment by jmo1121109** [comment]
Our site requires emails and we make the promise to our members that it will not be handing it out. Making this change would allow anyone online to easily harvest it. Regardless of that point, it still opens us up for attacks that would overwhelm our processing capacity and bring the site down or slow it.

**Comment by marknsikora** [comment]
1. Users have a setting to hide their email address. As far as I'm aware the default is off since I don't remember changing it.
2. Even extremely rudimentary rate limiting would solve this.

**Comment by TimothyJones** [comment]
We actually already have rudimentary rate limiting, (one profile search every 5 seconds) so I don't foresee this being a problem.

User profiles are already visible to guests, just the search page isn't. 

Since the IDs are sequential, dedicated people can crawl the user profiles anyway- and the site withstands even aggressive crawling of profile pages. It's happened before with no issues.

I think most members are aware of the possible consequences of publishing their email addresses, and as Mark points out, it's opt in anyway.

I don't foresee this change introducing any (new) problems.

**Comment by jmo1121109** [comment]
Another one of your issues is to turn off rate limiting. So just know that turning it off would remove the possibility of allowing this change.

**Comment by TimothyJones** [comment]
@marknsikora I've fixed this, and added a link to the user search on the login page. Thanks for the report!
