### ISSUE TITLE
move/support order bug

### ISSUE THREAD

**Issue by andersolesen80** [kestasjk/webDiplomacy#161]
In a game I have a fleet going Rum->Bulg(ec) and a fleet in Con with the order F Con S (F Rum->bulg(ec))

When I look at the orders submitted it shows me that those orders are not possible. which they should be i believe.
here's a look at it
http://webdiplomacy.net/map.php?gameID=165626&turn=7&preview&noCache=8941&mapType=large

**Comment by TimothyJones** [comment]
Looks fine to me:

<img width="709" alt="screen shot 2015-08-11 at 8 09 14 pm" src="https://cloud.githubusercontent.com/assets/914369/9195267/e29e5b9c-4064-11e5-8e56-4e3a6ce5c58b.png">

Do you have the orders the wrong way round? Note that webdip's format is "F Con support TO Bul from Rum" not the other way around.

We should make the standard format an option at some point.

**Comment by andersolesen80** [comment]
oh there was a mistake in the link, should be correct now. please have a look again 
http://webdiplomacy.net/map.php?gameID=165626&turn=6&preview&noCache=2849&mapType=large

**Comment by TimothyJones** [comment]
Oh, I see what you're saying (the preview link doesn't work for me, because I'm not logged in to your account).

I think this is the same issue as issue #82, combined with a known issue that wasn't previously reported (now reported in #162).

Both bugs are visual only, and the orders will process correctly.

Thanks for the report! This is really helpful.

**Comment by andersolesen80** [comment]
cheers 


     Den 12:49 tirsdag den 11. august 2015 skrev Timothy Jones <notifications@github.com>:
   

 Oh, I see what you're saying (the preview link doesn't work for me, because I'm not logged in to your account).I think this is the same issue as issue #82, combined with a known issue that wasn't previously reported (now reported in #162).Both bugs are visual only, and the orders will process correctly.Thanks for the report! This is really helpful.—
