### ISSUE TITLE
Profile search should redirect to the profile page

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#165]
Currently a profile search directs the user to "profile.php", meaning that the url doesn't contain the user ID, and can't be bookmarked or copy/pasted. This is annoying for organising tournaments and other moderator tasks that involve finding users by their username or email address.

The profile search should do a 302 redirect to the relevant profile page.

**Comment by jmo1121109** [comment]
Addressed by https://github.com/kestasjk/webDiplomacy/pull/709, will be made live to all members shortly.
