### ISSUE TITLE
(D) points icon conversion is a little aggressive

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#172]
The forum converts any number followed by a D or the word "points" to the points icon. This is a little aggressive, and affects some URLs or discussions of other scoring systems. It should probably be pared back to only converting `(d)` or `(D)`.

**Comment by yewang** [comment]
Seems that this issue can be closed, as it has been addressed by https://github.com/kestasjk/webDiplomacy/pull/230

**Comment by TimothyJones** [comment]
Good catch. I've been travelling so have been neglecting the notifications.
