### ISSUE TITLE
Moderators should have the ability to toggle whether a game is anonymous

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#173]
For some reason, the admin control panel is missing the ability to toggle the anon status of a game. This is a problem when players accidentally create games as non-anon when they meant anon (or vice versa).

**Comment by jmo1121109** [comment]
So this in my view is not a problem. If you make a game non-anon then you are better off remaking the game. Especially if the game has started already, there is no way to know who has already seen the game and noted who is who. And going from an anon game to a non anon game again is not a likely scenario. I've never seen a request for this actually to the mod team in over 5 years of modding. So I'm closing this out.
