### ISSUE TITLE
Allow reliability breakdown to be visible to all

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#177]
It would be an improvement if the reliability breakdown on the profile page was available to anyone looking at the profile. This allows users to make more informed decisions about the reliability of other players.

RR issues in anonymous games that are still in progress should not present in detail on the RR breakdown (unless it's the user's own profile page, or the user looking at the page is a moderator). These statistics could be presented to in aggregate, eg "Additionally N Civil Disorders were found in ongoing anonymous games".

**Comment by thorfi** [comment]
I liked the suggestion in a forum thread of also presenting "last time of CD / NMR" (rounded up to weeks) on profile page directly. :-)

**Comment by TimothyJones** [comment]
I would prefer to only have one number on the profile page related to reliability (otherwise people will call for the ability to gate by each type of expression - and there's no need to make it over complex).

I also support a better formula for RR, once we figure one out.

**Comment by thorfi** [comment]
Makes sense. I guess if you're making the RR breakdown available people can just go look. Might still be good to put  "last time of CD / NMR" (rounded up to weeks) on the breakdown page in case of anonymous game CD/NMRs though.

**Comment by jmo1121109** [comment]
Due to problems around anon and even displaying an increased count in records in games, this is not going to be a possible improvement. Closing this out.
