### ISSUE TITLE
Javascript issue on the world map

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#178]
When there are a lot of possible convoy routes (eg, when all the seas are full on the world map), the board can sometimes kill the browser. From a member:

> In one of my games, I don't seem to be able to give move orders requiring a convoy. (gameID=162651)
> 
> e.g. if I try to order South Australia to Thailand, I get a series of "Warning: Unresponsive script" errors in Firefox:
> 
> A) "Script: http://webdiplomacy.net/contrib/js/prototype.js:763"
> 
> Then if I continue (rather than kill) each one, I get (infinitely?) more such errors:
> 
> B) "Script: http://webdiplomacy.net/javascript/board/model.js?ver=4:59"
> C) "Script: http://webdiplomacy.net/contrib/js/prototype.js:703"
> D) "Script: http://webdiplomacy.net/javascript/board/model.js?ver=4:326"
> I don't know if there is ever a point where this will end, but it's very tedious, so I've not checked further.
>  If I cancel at that point and try to save the move, I get this from your page:
> "Parameter 'toTerrID' set to invalid value '133'"

**Comment by TimothyJones** [comment]
@Sleepcap - is this fixed on vDiplomacy? I had a peek through the javascript files you've modified, but I couldn't see anything obvious that was a fix for this.

**Comment by Sleepcap** [comment]
It does not do the validation of these largemaps in the javascript-code.
It's not really a fix, more a "duct tape"...
