### ISSUE TITLE
Reject accounts that try to signup with disposable email addresses

### ISSUE THREAD

**Issue by HellenicRiot** [kestasjk/webDiplomacy#179]
So ghug and I had an idea in the Mod Chat after I banned someone with a disposable email (Rule 8 violation, and usually used by people who are up to no good anyway) - could we get the site to email us flag up accounts with common disposable email addresses, or just reject them as acceptable email addresses on signup? 

https://gist.github.com/adamloving/4401361 is a pretty good list of the most common disposable email addresses.

HR

**Comment by TimothyJones** [comment]
I'll accept this change request. I like the idea of immediate rejection on signup - it's part of the site rules anyway.

We should figure out a way to make the site rules more clear on account signup.

**Comment by jmo1121109** [comment]
This is not something we are looking to do.
