### ISSUE TITLE
Game Setting Request: "No Replacements"

### ISSUE THREAD

**Issue by thorfi** [kestasjk/webDiplomacy#183]
A small? but significant group of players would prefer to have games where CD powers are *not* allowed to be replaced. This seems like it would be a sensible game setting option to have.

From http://webdiplomacy.net/forum.php?threadID=1297914

**Comment by thorfi** [comment]
From http://webdiplomacy.net/forum.php?threadID=1297914

**Comment by TimothyJones** [comment]
The feeling of the team is that we want to avoid having too many niche options, else our game setup screen starts looking like an aeroplane dashboard.

Typically, when a player says "I don't want replacements, let's play on", it's only the player who would benefit from not having a replacement.

Players have asked for better handling of NMRs and replacements, though. There's a lot of scope for improvement. Issue #143 is intended to address this.
