### ISSUE TITLE
"Investigate" button in-game

### ISSUE THREAD

**Issue by 2ndWhiteLine** [kestasjk/webDiplomacy#184]
Idea: add an "Investigate" button to the admin actions at the bottom of the game page that automates several tasks:
- Force pauses the game
- Inserts the standard mod investigation post
- Adds the game to the lead mod's spectate list for followup (optional)

For the future, we could even take this one step further and create an "investigations" tab for mods that would display all games toggled to investigate mode so that we can easily check and see what we forgot to cancel or follow up.

**Comment by jmo1121109** [comment]
Various mod changes have rendered this not needed
