### ISSUE TITLE
Typo on Ancient Mediterranean variant

### ISSUE THREAD

**Issue by beniliusbob** [kestasjk/webDiplomacy#186]
"Gulf of Sytris" on map is "Gulf of Syrtis" in dropdowns.

**Comment by TimothyJones** [comment]
Good catch. I believe [Syrtis](https://en.wikipedia.org/wiki/Gulf_of_Sidra) is correct.

**Comment by yewang** [comment]
Addressed by merged PR https://github.com/kestasjk/webDiplomacy/pull/240
