### ISSUE TITLE
Busy script on world maps with lots of fleets in the ocean

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#189]
There is an issue with the javascript for calculating convoys that causes unresponsive script (and the inability to enter orders) when the world map has many fleets in the ocean.

This is probably responsible for webdip using a lot of battery on mobile, too.

I'm not sure what the problem is, more investigation is needed.

**Comment by diptobi1** [comment]
Just a notice I might have solved this issue by rewriting and optimizing the algorithm to find Convoy paths: 
The new code has just been included on vdip and might be a good candidate to be ported over here, too, after some time of testing on vdip. Tests on a WWIV-map with busy waters (so one of the hardest stress tests available with vdips set of variants) showed a significant improvement (non-responsive to runtimes of under 100 ms).

For the time being the changes can be found here:
https://github.com/Sleepcap/vDiplomacy/commit/1686d60b58eec754a3b6ddcbb02b0dd52ae0a88a#diff-c2d37d311b98764477115723be296471
