### ISSUE TITLE
Bug trying to Join Game from Board view

### ISSUE THREAD

**Issue by thorfi** [kestasjk/webDiplomacy#195]
Fatal error: Call to undefined method processGame::titleBarName() in /usr/local/www/apache24/data/webdiplomacy/board.php on line 46

**Comment by thorfi** [comment]
ping @TimothyJones @deltachemist 

P.S.: Is this the right procedure for reporting this, or should I have been finding the previous issue to report this bug on?

**Comment by TimothyJones** [comment]
Yes, this is the right procedure. Thanks, I've fixed it. Improper testing!

**Comment by TimothyJones** [comment]
Much appreciated!

**Comment by thorfi** [comment]
Woot! \o/
