### ISSUE TITLE
Prevent wins during the retreat phase

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#196]
Currently, the territories change hands at the end of the Diplomacy phase, regardless of whether or not there are retreats. This means that it's possible for a country to win at 18 centres when a retreat could have put them back below 17. This should be fixed as a matter of priority.

Ideally the fix would only allow the retreats phase if it is possible for the retreat to put the country back below 18. However, it would still be an improvement to wait until the end of the retreats to change ownership of territories.

This is a change that requires careful testing. Any mistakes when working on the adjudicator could have major consequences to ongoing games.

**Comment by plund** [comment]
See also #261 reporting a very similar issue.
