### ISSUE TITLE
Increase the default join time for games

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#198]
Currently, games have a joining period of the same length as the phase. This doesn't make sense for 24 hour games (and is tight for 48 hours). 

We should increase the default to something like double (or maybe a set length eg 7 days) of join period for non-live games.

Live games should have a better default too- eg 30 mins.

**Comment by jmo1121109** [comment]
Default join time has been updated via the recent changes to RR and extended phases.
