### ISSUE TITLE
World Map Visual Bug

### ISSUE THREAD

**Issue by leon1122** [kestasjk/webDiplomacy#202]
The coastal outline for BAT is the Brazilian green color rather than black.

**Comment by TimothyJones** [comment]
This occurs on the small map only, and doesn't immediately appear to be tied to any land territory.

**Comment by TimothyJones** [comment]
Thanks for the report!

**Comment by leon1122** [comment]
I just noticed that this outline is also present on all or part of the shorelines of Mexico, Monterrey, Yukon Territory, Quebec, Colombia, France, Balkans, Yakutsk, and possibly other provinces.

**Comment by jmo1121109** [comment]
resolved years ago
