### ISSUE TITLE
World Map F Moscow not adjacent to Armenia

### ISSUE THREAD

**Issue by jkuta** [kestasjk/webDiplomacy#204]
On the World Map, a fleet in Moscow cannot move to Armenia. The world map makes this appear to be possible, even though Armenia is a landlocked country.

Possible solutions:

1) The border between Armenia and Black Sea could be colored RED to show fleets may not access it, and update variant notes on site.
2) Rename Armenia to Caucasus and allow fleets to use the border as normal.

**Comment by TimothyJones** [comment]
Thanks for the report! This is fixed in #203 - now fleets can move to Armenia.

The point about the naming is well made, but since the naming of the territory is described in the original variant rules (before it came to webdiplomacy), I think we'll retain Armenia.
