### ISSUE TITLE
Modern Map: Convoy Bug Kaz across Caspian

### ISSUE THREAD

**Issue by jkuta** [kestasjk/webDiplomacy#205]
On the Modern Map, a fleet in the Caspian Sea cannot convoy an army in Kazakhstan to either Caucasus or Azerbaijan. I assume the return trip is also disallowed.  All convoys across the Caspian Sea might need checking.

**Comment by TimothyJones** [comment]
Thanks for the report!

**Comment by HellenicRiot** [comment]
I made a pull request for this bug.

**Comment by TimothyJones** [comment]
Fixed by #275
