### ISSUE TITLE
Global Status Update for NMRs, CDs

### ISSUE THREAD

**Issue by jkuta** [kestasjk/webDiplomacy#206]
During anonymous games, it is often difficult to know whether a player has NMR'd the first time.  It is also not always clear when someone CD's. It is also not clear when someone takes over a Great Power which was in CD.

I would like to see the Global chat window have several messages such as:

"Spring, 1901: France failed to submit orders."
"Autumn, 1901: France has fallen into civil disorder."
"Spring, 1902: [UserName/"Someone"] has taken over France."

**Comment by TimothyJones** [comment]
The site used to do this before my time - I'm not sure why it was changed. We should figure out if there's a good reason it was changed before changing it back - but otherwise this seems like a good change to make.
