### ISSUE TITLE
Reorder "Game stats:" display

### ISSUE THREAD

**Issue by jkuta** [kestasjk/webDiplomacy#210]
IMO, "Game stats:" on each player profile should be reordered as below:

Won:
Drawn:
Survived:
Defeated:
Total (finished):
Playing:
[gap]
Civil disorder:
Civil disorders taken over:
No moves received / received:
Reliability Rating:

**Comment by TimothyJones** [comment]
Can you elaborate on why this would be an improvement?

**Comment by jkuta** [comment]
IMO

Wins / Draw / Survive / Defeat

most accurately prioritizes the Object of the Game.

Moving Total (finished) lines up the summation.

The last block all deal with reliability, even if they aren't all used in the calculation.

**Comment by TimothyJones** [comment]
Seems reasonable. I'll accept this.
