### ISSUE TITLE
Problem: Army in Tarraconensis can issue move order to Baleares

### ISSUE THREAD

**Issue by jkuta** [kestasjk/webDiplomacy#216]
Ancient Mediterranean map. Order can be issued, but result is failure. Might also check Saguntum <=> Baleares also.

**Comment by TimothyJones** [comment]
Can you explain what you mean by "result is failure"? What happens?

**Comment by jkuta** [comment]
The order fails. Per the map rules:
_Baleares

Baleares is a single space (which consists of the islands and the water around them). Since it contains both land and water, it can be occupied by a fleet or an army. However, since it is a single space, it can only be occupied by one unit at a time. Although an army can occupy Baleares, it can not move there directly from the mainland spaces since the islands are too far from the coast. For an army to enter or leave Baleares, it would have to be convoyed by a fleet in the Berber Sea or the Ligurian Sea. Since Baleares consists mostly of water, it is considered a sea space for the purposes of convoys, therefore a fleet occupying Baleares may be used to convoy an army using the normal convoy rules. Baleares is a supply center.  _

So armies should not be able to issue orders to move to Baleares *except* via convoy. If the order is issued normally "via land" it will simply fail.

**Comment by TimothyJones** [comment]
I think this is the same issue as #104?

**Comment by jkuta** [comment]
Yes, it would appear to be the same.
