### ISSUE TITLE
Problem: World Map (Fleet in Moscow)

### ISSUE THREAD

**Issue by jkuta** [kestasjk/webDiplomacy#217]
Problem: World Map Fleet in Moscow can only go to Black Sea, not Armenia or Ukraine.

**Comment by HellenicRiot** [comment]
I believe this is already fixed - I went to fix it today and was unable to replicate, and I've found games on the site where this move has been made recently.

**Comment by TimothyJones** [comment]
Great! Maybe Jmo fixed it when he was changing variants. Or maybe one of us did it and forgot.
