### ISSUE TITLE
URL section on profile page should be truncated

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#218]
If the URL/homepage field on a user's profile is very long, then the text overlaps with the statistics section:

![screen shot 2016-02-01 at 2 36 46 pm](https://cloud.githubusercontent.com/assets/914369/12708216/4781235e-c8f1-11e5-8d30-3174f90dc266.png)

Instead, the text should be truncated or wrap.

**Comment by yewang** [comment]
Addressed by merged PR https://github.com/kestasjk/webDiplomacy/pull/239

**Comment by jmo1121109** [comment]
This is fixed, closing out.
