### ISSUE TITLE
Detailed statistics page

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#220]
It would be excellent to have a more detailed statistics page as part of member profiles, allowing graphs to be drawn showing game results, and filters to be applied to remove eg gunboat games/variants etc.

This is a fairly loosely defined feature - whoever picks it up would have significant freedom to design how the reporting works.

Graph generation should be done client side in JavaScript.

**Comment by jmo1121109** [comment]
This is effectively done. Release coming in a couple days, closing to make sure no one picks up in meantime.
