### ISSUE TITLE
Pulling list of games that are marked 'spectated'

### ISSUE THREAD

**Issue by TheMinisterOfWar** [kestasjk/webDiplomacy#224]
For integration in other websites, I'm looking for a way to pull a custom list of games. Ideally it would involve different criteria (for example, user X or Y is in there), but even a link to pulling 'Games user X is spectating' would go a long way.

**Comment by TimothyJones** [comment]
This is a really cool idea - it would be cool if we had an (authenticated) API for members to build services on. This would potentially be a nice way around our lack of email notifications.

**Comment by TheMinisterOfWar** [comment]
Agreed. I was thinking an API, but that may be too ambitious to start with. Pulling the spectated games may be a decent first step.

**Comment by jmo1121109** [comment]
This is not entirely feasible as a starting point for an api service. Going to close this out, when we eventually have an api it will be kept in mind.
