### ISSUE TITLE
CSS: Chat text doesn't wrap

### ISSUE THREAD

**Issue by LitterPicker** [kestasjk/webDiplomacy#228]
A player sent me a chat message reading "With what!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?!?!??!?!?!?!?!?!!!!?!!!??!?!??!!?!?!??!?!?!?!?!??!?!?!?!??!?!?!!??!?!?!?!?!!!????!?!?!??!"
There were undoubtedly a few more !s and ?s after that, but the end of the message cannot be read, and neither, now, can the ends of long lines in other messages.
My response, for example:
"Do you want to keep playing? I'll give you your country back if you like. There would be some conditions, of co"
That's not quite what I wrote.

**Comment by TimothyJones** [comment]
This is probably just a CSS change. What browser are you using? My browser (Chrome) adds a horizontal scroll bar when this happens.

Either way, I believe a workaround is to highlight the text and copy/paste it out.

**Comment by LitterPicker** [comment]
I generally use Firefox, but I checked the chat in Chrome, and I don't see a horizontal scroll bar.

**Comment by jmo1121109** [comment]
Tested this out in depth, can no longer replicate and looks corrected in the css. Closing this out.
