### ISSUE TITLE
support move display bug in preview mode?

### ISSUE THREAD

**Issue by suprstar** [kestasjk/webDiplomacy#231]
I see what I hope is just a display bug in my moves.  I have western med moving to spain (sc), and I want gulf of lyons to support that move.  The pulldown for 'to:' in the gulf of lyons support move doesn't include 'Spain (sc)' just 'Spain'.  Will this support work?

Gulf of lyons can move to Spain (sc):
![move](https://cloud.githubusercontent.com/assets/15369291/14727425/bc5ba3ac-07f8-11e6-937b-04d6bf5c8ba0.png)

but can only support-move to Spain:
![supportmove](https://cloud.githubusercontent.com/assets/15369291/14727427/c32aba42-07f8-11e6-846d-05e83f52a373.jpg)

The moves look like I'm supporting a move that isn't being made, I see the gray arrow indicating that on the preview:
![selection_246](https://cloud.githubusercontent.com/assets/15369291/14727433/d1f8792e-07f8-11e6-9539-555bfd9a9e7d.jpg)

**Comment by TimothyJones** [comment]
Thanks for the report! This is the same as issue #82, and it is indeed a display only bug. Unfortunately, a fix for this is somewhat complex.

Ideally, it will be fixed when we update the map.
