### ISSUE TITLE
Design forum

### ISSUE THREAD

**Issue by plund** [kestasjk/webDiplomacy#234]
Looking for some kind of Design forum for webdiplomacy.net and vdiplomacy.com. Is this it? 

Peter Lund  
(user: peterlund on both gaming sites)

**Comment by TimothyJones** [comment]
I'm not sure I understand what you're looking for?

**Comment by plund** [comment]
Is github issues the best way to ask fellow webdiplomacy.net/vdiplomacy.com coders/testers questions about installation/test/code ?

Is the codebase the same for both sites?

**Comment by TimothyJones** [comment]
The code base isn't the same, although they share a lot of common code. vDiplomacy can be found at https://github.com/Sleepcap/vDiplomacy

If you have a question about webdiplomacy development, the best place for it is currently webdipmod@gmail.com. We used to have a developer forum, but it went unused and got filled with spam, so it was retired.

If you have a feature request, it can go in the webdip forum, by email to the address above, or as a new issue here.

If you're having trouble installing a development environment or have other questions, then webdipmod@gmail.com is the way to go.
