### ISSUE TITLE
Turn off defeat announcements in FoW games.

### ISSUE THREAD

**Issue by plund** [kestasjk/webDiplomacy#236]
Assuming that also vdiplomacy.com issues are handled here. 
In my EOG statements in http://www.vdiplomacy.com/board.php?gameID=26439 I wrote: 
One disturbing thing is that there was an announcement done by the server to everyone when Turkey had been defeated. It made it impossible for me and Italy to give France the impression that the fight against Turkey was slow and ongoing. For FoW games this announcement should be turned off.

**Comment by TimothyJones** [comment]
This should be reported over at https://github.com/Sleepcap/vDiplomacy
