### ISSUE TITLE
After Installation DACT Fails

### ISSUE THREAD

**Issue by bornhaeusser** [kestasjk/webDiplomacy#237]
Hi I want to run DACT Test in Maintanace Mode. But it fails with:

Error triggered: Missing argument 11 for processGame::create(), called in /volume1/web/game/webdiplomacy/datc/datcGame.php on line 60 and defined

Error: "Missing argument 11 for processGame::create(), called in /volume1/web/game/webdiplomacy/datc/datcGame.php on line 60 and defined"
Raised: "/volume1/web/game/webdiplomacy/gamemaster/game.php"
Line: "289"
userID = 5Variable dump: variantID => 1
name => DATC-Adjudicator-Test
password => 
bet => 5
potType => Winner-takes-all
phaseMinutes => 30
joinPeriod => 30
anon => No
press => Regular
missingPlayerPolicy => Normal

Trace:
0 => Array: (
file => /volume1/web/game/webdiplomacy/gamemaster/game.php
line => 289
function => error_handler
args => Array: (
0 => 2
1 => Missing argument 11 for processGame::create(), called in /volume1/web/game/webdiplomacy/datc/datcGame.php on line 60 and defined
2 => /volume1/web/game/webdiplomacy/gamemaster/game.php
3 => 289
4 => Array: (
variantID => 1
name => DATC-Adjudicator-Test
password => 
bet => 5
potType => Winner-takes-all
phaseMinutes => 30
joinPeriod => 30
anon => No
press => Regular
missingPlayerPolicy => Normal
)
)
)
1 => Array: (
file => /volume1/web/game/webdiplomacy/datc/datcGame.php
line => 60
function => create
class => processGame
type => ::
args => Array: (
0 => 1
1 => DATC-Adjudicator-Test
2 => 
3 => 5
4 => Winner-takes-all
5 => 30
6 => 30
7 => No
8 => Regular
)
)
2 => Array: (
file => /volume1/web/game/webdiplomacy/datc/interactive.php
line => 160
function => __construct
class => datcGame
object => Array: (
id => 
variantID => 
Variant => 
password => 
turn => 
phase => 
attempts => 
processTime => 
private => 
name => 
gameOver => 
pot => 
phaseMinutes => 
Members => 
Scoring => 
potType => 
drawType => 
processStatus => 
pauseTimeRemaining => 
minimumBet => 
anon => 
pressType => 
lockMode => 
missingPlayerPolicy => 
minimumReliabilityRating => 
civilDisorderInfo => 
)
type => ->
args => Array: (
0 => 101
)
)
3 => Array: (
file => /volume1/web/game/webdiplomacy/datc.php
line => 33
args => Array: (
0 => /volume1/web/game/webdiplomacy/datc/interactive.php
)
function => require_once
)
.

This was probably caused by a software bug. If these occur often try enabling error-logging via config.php, and report errors to the official devs for help.

Also in the Buttom of the Start Page and on several other PAges i have in the Bottum BAd Querrys:

Total query time:   0.0028951168060303 sec
Average query time: 0.00019300778706868 sec
Slowest query:  0.00085210800170898 sec
Bad queries:

0.00085210800170898 sec SELECT g.id, g.variantID, g.name, g.phase, m.orderStatus, m.countryID, (m.newMessagesFrom+0) as newMessagesFrom, g.processStatus FROM wD_Members m INNER JOIN wD_Games g ON ( m.gameID = g.id ) WHERE m.userID = 5 AND ( ( NOT m.orderStatus LIKE '%Ready%' AND NOT m.orderStatus LIKE '%None%' AND g.phase != 'Finished' ) OR NOT ( (m.newMessagesFrom+0) = 0 ) ) ORDER BY g.processStatus ASC, g.processTime ASC
0.00050711631774902 sec SELECT g.\* FROM wD_Games g WHERE g.phase = 'Pre-game' AND g.phaseMinutes < 60 AND g.password IS NULL ORDER BY g.processStatus ASC, g.processTime ASC LIMIT 3
0.00052404403686523 sec SELECT \* FROM wD_Notices WHERE toUserID=5 ORDER BY timeSent DESC LIMIT 35
0.00050091743469238 sec SELECT g.\* FROM wD_Games g INNER JOIN wD_Members m ON ( m.userID = 5 AND m.gameID = g.id ) WHERE NOT g.phase = 'Finished' ORDER BY g.processStatus ASC, g.processTime ASC
0.00051093101501465 sec SELECT g.\* FROM wD_Games g INNER JOIN wD_WatchedGames w ON ( w.userID = 5 AND w.gameID = g.id ) WHERE NOT g.phase = 'Finished' ORDER BY g.processStatus ASC, g.processTime ASC

Missed localization lookups:

JavaScript localization lookup failures:

**Comment by TimothyJones** [comment]
Hi, I'm travelling at the moment, but I'll have a look in to this as soon as I can.

**Comment by kestasjk** [comment]
Looks like some new game settings have been added that don't have defaults. If you alter
[https://github.com/kestasjk/webDiplomacy/blob/master/gamemaster/game.php#L289](url)
to be
`public static function create($variantID, $name, $password, $bet, $potType, $phaseMinutes, $joinPeriod, $anon, $press, $missingPlayerPolicy='Normal', $drawType='draw-votes-public', $rrLimit=1)
`

It should work

**Comment by bornhaeusser** [comment]
new installation works great.
