### ISSUE TITLE
Remove country selection weight

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#245]
As per #235, the country selection weighter does not work correctly. Perhaps we should just remove it and make it random again.

**Comment by rjmcf** [comment]
The country selection problem is a version of the Assignment Problem, which has an optimal solution in the Hungarian Algorithm. I will implement this and see how long it takes to assign countries, if it's anything more than a few seconds then I'll just go about making selection random again.

**Comment by TimothyJones** [comment]
This is great! Thanks!

It’s worth noting that the country selection weighting is also currently broken (the previous weights are not saved correctly because an update statement should be a create or update). I’m on mobile so it’s a bit of a pain to pull up the issue number- but I’ll link it when I get to a computer.

**Comment by rjmcf** [comment]
No worries! Is it the one that you linked above? I'll have a look at that too while I'm here.

**Comment by TimothyJones** [comment]
Aha! Yes, it is. Thanks very much!

**Comment by rjmcf** [comment]
I've implemented the algorithm in Python (as I'm more familiar with it and it's easier to prototype in), and even with 10x10 (I think the largest variant type we have?) the solution is basically instantaneous, so this looks very viable. I'll get to work implementing it in PHP and then see if I can slot it in to the codebase.

**Comment by TimothyJones** [comment]
Awesome! Looking forward to seeing what you come up with.

**Comment by rjmcf** [comment]
Right, I now have a php class implementing the algorithm, which I've tested with a parser, so I know it can do what it needs to do. It's pretty fast to do the 10x10 problem, like less than a second. There are a few issues to deal with now I think. 

0). What's the best way to test this on a server like the one it'll be operating on? I don't want to take up precious time from other important procedures.
1). I need to make sure the coding style, comments etc is aligned with the codebase. That hopefully shouldn't take too long.
2). I'll need to look at how to slot it in where it's needed. I have some ideas for how to do that, but it's just something else that needs doing.

Cheers!

**Comment by rjmcf** [comment]
Ok I've edited the coding style so it's hopefully more in line, I've also edited pregame.php locally so it should be ready to go. Before I make a pull request I would like to try and test it in place, but I'm not sure what's best. How do you guys test new code before? Have you set up your own webservers and databases at home?

**Comment by TimothyJones** [comment]
Yes, usually we've just set up a dev machine. It's pretty straightforward, but I've written a harness to do this for you in docker, that you can find here: https://github.com/TimothyJones/webDiplomacy-dev-docker

**Comment by rjmcf** [comment]
Thank you! I'm getting an error in localhost saying:
"Database version 1.42 and code version 1.43 don't match, and no auto-update script is available for this version. Please wait while the admin runs update.sql". I'll have a look around at some of the developer forum etc to see if this is known about but I thought I'd post it here too.

**Comment by TimothyJones** [comment]
Yes, sorry about that. It’s because the live database was temporarily a slightly different shape. Feel free to change the database version to 143 - it’s safe and I should have done it already.

**Comment by rjmcf** [comment]
Ah, how would I do that? Also the DATC tests that I just remembered about are causing an error, it's the outputTest of datcGame specifically. I can post the error logs if that would help.

**Comment by rjmcf** [comment]
Oh is it literally making a new folder, making a new readme.txt file saying something like "keeping up with code", then a new update.sql file with
`UPDATE `wD_Misc` SET `value` = '143' WHERE `name` = 'Version';`
in it?

**Comment by rjmcf** [comment]
DATC tests are no longer throwing an error (I think I started debugging logs but may have accidentally touched something else? I'm not sure) but now none of the tests are passing. I'm assuming that is intentional, since it could also mean that it hasn't been run.

**Comment by rjmcf** [comment]
I've just realised I'm a complete idiot and I've completely misinterpreted the old version of this code. How difficult would it be to change the schema for wd_Users so that it stores the number of times a country has been played as, rather than the chance of playing that country?

**Comment by TimothyJones** [comment]
Sorry for the slow replies, been at work. I'm fine with that change,
although from memory I don't think that information is in wD_Users at all?
I thought it was in VariantData or something similar.

**Comment by rjmcf** [comment]
No worries. You're totally right though, it is in VariantData, it's just that there's a comment in the old code saying it's in wd_Users and I've never quite been able to get that out of my mind even when I figured out it was wrong and disregarded it.

This looks like it'll be a database update, in order to get rid of all users current values for chances. Is there a way that we can fill in correct values for current users (based on old games) or will we just start everyone at 0 plays and go from there in the knowledge that it shouldn't be a problem anymore?

**Comment by TimothyJones** [comment]
We could probably write a query to figure it out an populate it from past games, but unfortunately I have very little time to spend on webdip updates (reviews and PRs and that’s about it). I’m happy to accept an update that starts over, though.

I should point out that the variant data entries aren’t created properly for new users though. We’d need to fix this if we rely on that table. I think an upsert is probably the right way to go, but I don’t know if MySQL supports that out of the box

**Comment by rjmcf** [comment]
I have a potential upsert substitute, but it only works with  SQL Server 2008 or later. Do you know which version we use, or how to find out?

**Comment by rjmcf** [comment]
(also is it ok for this one pull request to fix both of these issues?)

**Comment by TimothyJones** [comment]
`mysql  Ver 14.14 Distrib 5.5.57, for FreeBSD10.3 (amd64) using  5.2`

And yes, absolutely!

**Comment by rjmcf** [comment]
Just found out MySQL Server and SQL Server are in fact different things. However, there is something we can use I think called REPLACE in mysql, which uses Primary Keys to decide if a row is duplicate or not, updating if yes, inserting if no. (https://dev.mysql.com/doc/refman/5.5/en/replace.html) Luckily whoever set up VariantData is a GENIUS and not only is there an appropriate primary key, but there is also a completely unused val_int column which I can use to count the number of plays. That means no updates need to be done to current entries, we can just start using this column. Let me do some tests to make sure that REPLACE works as expected, then I'll start working on this.

**Comment by rjmcf** [comment]
REPLACE works exactly as we want it to. There is another issue though, why does VariantData store gameID? If we update the play count for each player for a given country in a given variant, that's stored in a particular row with a gameID. That means when we start a new game, we need new rows for every player for every country in that variant, and it also means that either we start of with default play counts of 0 again, or we have to find the latest game of this variant to get the old play counts from. As far as I can tell, the same applied when we were using chances, every time we were trying to assign countries, everybody was being given default chances for all countries. Correct me if I'm wrong, but that's how I'm interpreting the code currently.

My suggestion is that we stop storing gameID in VariantData. This makes sense, as the chances for a given player, variant, country don't depend on the gameID. We should be able to read a single row for each player, variant, country (,type?) combination, and update just that row when we assign countries.

**Comment by rjmcf** [comment]
I forgot to update to say that I'm an idiot, gameID is always 0. I should be putting in a pull request soon as I've got everything to work I think, just doing some more testing.

**Comment by rjmcf** [comment]
This issue can be closed right?

**Comment by TimothyJones** [comment]
Oh! Yes, good catch. Thanks.
