### ISSUE TITLE
Version 1.42  -  1.43

### ISSUE THREAD

**Issue by alexintour** [kestasjk/webDiplomacy#251]
It seems that from version 1.42 to 1.43 there were a lot of interesting improvements, but if I download the files to make a new installation the last available version is 1.42.

Is it right? will there be the 1.43 version ready to install too?

**Comment by TimothyJones** [comment]
The only updates present in 1.43 are the changes to allow the WDC game info to display in the menu/on a page of its own. It's available in a branch if you want to take a look, but it's not worth developing against, and won't be included in the master branch.

The next master release will be 1.44.

The version is only used for database changes- any updates that don't require database changes don't change the version number.

There are no features live on the site that are not in this repository. Are you having trouble getting your install fully functional?
