### ISSUE TITLE
Cheating in live game "Korr"

### ISSUE THREAD

**Issue by LionofNaples** [kestasjk/webDiplomacy#252]
http://webdiplomacy.net/board.php?gameID=196087

Does anyone else think it's strange that Germany and Russia perfectly coordinated moves in a live game that was anonymous without any chat whatsoever?

Also, I find it strange how Russia makes no moves in the end and allows Germany to completely take him over.

I think we have a multi scandal on our hands people!

**Comment by TimothyJones** [comment]
This is an issue for the moderators rather than a code change. I've forwarded it on to webdipmod@gmail.com (the address for the moderators found in the help page) for you.
