### ISSUE TITLE
Turn limited vDip games should end after possible retreats

### ISSUE THREAD

**Issue by plund** [kestasjk/webDiplomacy#261]
# Bug report

A game limited to 4 turns on vDip game ended directly after the autumn movement. One German army was dislodged in VEN and could retreat into 2 centers ROM owned by Italy and the neutral TRI, but the game was ended before the retreats could be made.

Here the test game is:
http://www.vdiplomacy.com/board.php?gameID=32471

## Expected behaviour

A turn limited vDip game should end after the autumn retreats. 

## Actual behaviour

The game was ended prematurely.

## Steps to reproduce

As in our test game http://www.vdiplomacy.com/board.php?gameID=32471

1 - set turns to 4
2 - make sure a unit is disloged in the autumn 1902 with viable retreat options into centeres it does not own.
3 - The unit is not given the chance to retreat into those centers.

**Comment by plund** [comment]
This one is related to issue #191 already found in this issue tracker.

**Comment by TimothyJones** [comment]
Thanks for the detailed reproduction steps. I'll close this issue so that we have all the discussion in one place.
