### ISSUE TITLE
When on a phone, post button in forum disappears after 4-5 lines written

### ISSUE THREAD

**Issue by TicTacToeNZ** [kestasjk/webDiplomacy#264]
An easy fix (I think) could be to move the button outside the text box, to where it is in a game when pming countries

**Comment by TimothyJones** [comment]
Are you on android? Which browser? The forum works fine on Safari and Chrome on iPhone.

**Comment by TimothyJones** [comment]
Everyone who has submitted fixes has only been able to test on iPhone - patches that solve android problems would be very welcome.

**Comment by TicTacToeNZ** [comment]
Yes I am on a Huawei p8 lite at the momet but this has been a problem on
all my past android devices. I am using Chrome and have not tested this on
any other browser. I am happy to test out the other browsers for you.

Thanks,
Thomas

**Comment by TicTacToeNZ** [comment]
On the chrome and Google apps, the button disappears however on the browser
app (which is horrible to use) it works perfectly

Thomas

**Comment by TicTacToeNZ** [comment]
Hi Kestasjk,
I have no idea how coding works in the slightest and how the hell you'd
actually do it or even if inspecting element is anything like you'd see,
but I'm pretty sure, moving the post reply button above the post box would
work. Something like whats attached? The only thing that could happen is
the close button disappears along with the number of replies. However I
have no idea as inspecting element on a phone is impossible. I'd be happy
to test it somehow. Better the close button than the post reply button,
right?

Thanks,
Thomas

**Comment by TicTacToeNZ** [comment]
also here is what it looks like on the computer, note I've also taken out
the bottom 'hrthin'

**Comment by TimothyJones** [comment]
Hi @TicTacToeNZ - your images aren't coming through. But, this may be addressed in a recent pull request #267, from @Zjcompt.

You can check it out on vdip at the moment, and we'll be trialling it on webdip soon.

**Comment by TimothyJones** [comment]
In unrelated news, I remember your username from my geocaching days when I lived in New Zealand. Are you the same TicTacToeNZ?

**Comment by TicTacToeNZ** [comment]
Sweet thanks, looks like its sorted.
Also yes? I've only ever done 3 around the south coast of wellington a
couple of months ago, but I've signed up as TicTacToeNZ, that's pretty
amazing to be honest, wasn't expecting to be pulled up because of 3
geocaches I did

**Comment by negaffney** [comment]
I can confirm that #267 fixes this at least on Chrome/Galaxy S7.

**Comment by TicTacToeNZ** [comment]
Yip, it works perfectly, thanks kestasjk :)

**Comment by TimothyJones** [comment]
Great!
