### ISSUE TITLE
NMR wrongly credited on ready and unready of holds

### ISSUE THREAD

**Issue by negaffney** [kestasjk/webDiplomacy#265]
# Bug report

When a player readies all holds and then unreadies them (leaving them saved), and does not save any other orders at any point during that phase, the player is credited with an NMR in their reliability statistics. 

## Expected behaviour

The player should not be credited with an NMR in such instances. 

## Actual behaviour

The player is credited with an NMR. 

## Steps to reproduce

In a new phase of any game, click ready immediately without editing any orders, and then click unready and leave the orders alone for the rest of the phase.

**Comment by TimothyJones** [comment]
Nice catch. This might be annoying to fix due to the way NMRs are detected, but we should definitely fix it.

**Comment by jmo1121109** [comment]
Fixed by bo's pr.
