### ISSUE TITLE
Improve wording around password box

### ISSUE THREAD

**Issue by NathanMaton** [kestasjk/webDiplomacy#266]
# Bug report

I go to the games page, look for games I can join and then click join. On the next page I get this error message: The password you supplied is incorrect, please try again.

## Expected behaviour

Confirmation I joined the game.

## Actual behaviour

I go to the games page, look for games I can join and then click join. On the next page I get this error message: The password you supplied is incorrect, please try again.

## Steps to reproduce

On Chrome, go to games page and try joining a game. I also tried logging off and back on and that didn't fix it. I did also try creating a game which I was successfully able to do.

**Comment by negaffney** [comment]
It looks to me like you're trying to join a private (password-protected) game without supplying a password. webDip has the functionality for creating private games to allow for friends to play with each other and for users to organize special games and tournaments. Try joining a game that doesn't have a lock icon next to the name or a password field below "Bet to join:"

**Comment by TimothyJones** [comment]
@negaffney is correct - webdiplomacy is asking for the game password, rather than your user password.

This workflow is confusing - we should change the "password" box to say "game password".

**Comment by jmo1121109** [comment]
This was corrected by https://github.com/kestasjk/webDiplomacy/pull/298

**Comment by TimothyJones** [comment]
Thanks everyone!
