### ISSUE TITLE
Add ability to have hidden moderators

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#270]
The change to profile.php in this commit introduced a hard-coded user ID to not get the moderator badge. We should add a user type of `hidden-mod` that provides this functionality instead. https://github.com/kestasjk/webDiplomacy/commit/02b4d492236936fe8fc410ef7420ea6506227685

The user type would only prevent display of the moderator badges, the actual moderator powers would be conferred by `Moderator` and `Admin` as usual.

**Comment by jmo1121109** [comment]
After discussion with the team this isn't really needed as a feature. Removed the reference to my userID in the code as well.
