### ISSUE TITLE
Remove site rules from version control

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#271]
It's pretty common for the site rules to be updated, which results in a lot of unnecessary commit churn (and the site often being out of sync with master, if changes are made directly).

We should remove the rules from version control, and have them auto included from an untracked and ignored file (that is not included if missing).

**Comment by jmo1121109** [comment]
This hasn't been an issue anymore and with the page's redesign I don't think this is necessary. Other sites will probably benefit from getting the rather nice layout we have for this page now.
