### ISSUE TITLE
Move the JS and CSS version parameters to global/definitions.php

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#278]
At the moment the parameter of the CSS-version is set directly in the code with the "&ver=" parameter in html.lib and the JS-Version is set mid-code too.
Maybe make this a GLOBAL variable, so it's easier to manage.

**Comment by Sleepcap** [comment]
Merging the code today I realozed the JD-Version is now defined 2 times in html.lib (line 390 and 920).
This should really move to global/definitions.php.

**Comment by jmo1121109** [comment]
This will need to include adding css versioning to all the css files too. Currently we only css cache bust some of the files.

**Comment by Sleepcap** [comment]
You do the CSS-versioning in the lib/html.php file too..
Would be much better defined in definitions.php.
It's really cluttered at the moment and makes updating the vDip-code unneccessary complex.
