### ISSUE TITLE
Remove second PM system

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#286]
The forum and the site both have a PM system. We don't need two (it's confusing and also unnecessary).

Probably the non-forum one is the best one to remove - this means we should:

* Give site banners when users have forum notifications (like the old PM system)
* Add links to user's forum profiles or game pages on the webdip profile pages
* We'll probably need to have a good way to handle users who have never logged into the forum (like auto creating accounts).

**Comment by stevenroose** [comment]
I can't access either. Where is the link to the in-game PM system?

**Comment by TimothyJones** [comment]
This issue is about the out-of-game pm systems. For in-game messaging in press enabled games, the pressbox is above the map.

**Comment by jmo1121109** [comment]
This has been addressed. Thanks @shdant113
