### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bornhaeusser** [kestasjk/webDiplomacy#288]
Hi, 
 
is it possible to hide the querry failure in admins buttmon of the page?

**Comment by TimothyJones** [comment]
This warning should only appear for admins. It's because admins are currently always in debug mode.

It's not currently possible, but it's probably worth adding an "admin mode"/"player mode" feature for admins.

**Comment by TimothyJones** [comment]
I've opened #293 , and I'll close this one. Feel free to reopen if you have further questions or feel that #293 doesn't address your concern.
