### ISSUE TITLE
Activate phpBB3 Forum on Start Page

### ISSUE THREAD

**Issue by bornhaeusser** [kestasjk/webDiplomacy#299]
Hi,
i didi not find the setting to put the phpbb3 Forum on my Start Page like on the webdiplomacy.
phpBB3 is working on my site but the start page shows:

Forum Link
No forum posts found, why not start one?

**Comment by TimothyJones** [comment]
@kestasjk any thoughts on this?

**Comment by kestasjk** [comment]
The procedure in here should still work as far as I know:
https://github.com/kestasjk/webDiplomacy/blob/master/contrib/phpBB3-files/README.txt

Have you definitely done every step as described?

**Comment by kestasjk** [comment]
Having looked into it I can see that I had made some uncommitted changes to index.php and lib/html.php regarding phpBB3 support, which were made directly to the live server. Now that I've got my dev server back up I'm testing this as a first dev->github->live commit.

**Comment by bornhaeusser** [comment]
Works now - thanks
