### ISSUE TITLE
New Forum Errors on Direct URL

### ISSUE THREAD

**Issue by jmo1121109** [kestasjk/webDiplomacy#302]
Logging in using http://95.211.128.12/webdiplomacy/logon.php works as it should except for anything involving the new forum, which results in:

Not Found
The requested URL /contrib/phpBB3/ was not found on this server.

**Comment by TimothyJones** [comment]
This might be site config rather than code - @kestasjk  ?

**Comment by kestasjk** [comment]
In my thinking the solution is blocking that URL rather than making the system have to work via an undocumented access point. Is there any reason you need that URL to work jmo?

________________________________

**Comment by jmo1121109** [comment]
Nope, that sounds fine to me.

**Comment by jmo1121109** [comment]
Closing this as the direct url was disabled during the migration to the new server.
