### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by bornhaeusser** [kestasjk/webDiplomacy#303]
Hi,

i translate the game in german. but i have an issue. could not find the correct string for translating the orders:

Example i want to change the market words:

![image](https://user-images.githubusercontent.com/6609040/36867753-65088f38-1d96-11e8-9afb-9e6c8bc1cbfc.png)

if you have also a tip where translate: hold, move, support, via land, etc....

**Comment by diptobi1** [comment]
Hi bornhaeusser, 
I am not in charge of webdip's github repository but I have already translated the website once. You might want to take a look at a fully German translation (of vdip):
https://github.com/ichtyst/diplwebsite
The strings for hold, move, support, via land etc should be translated via the interface in the AdminCP. The same goes for the marked words though they do not appear in the Dropdown-Menu itself in my installations if I am not mistaken.
