### ISSUE TITLE
PHP type error

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#304]
Newer PHP versions throw a type-error on any problems:
Fatal error: Uncaught TypeError: Argument 1 passed to exception_handler() must be an instance of Exception, instance of ParseError.
This can be solved by changing 
"function exception_handler(Exception $exception)"
to
"function exception_handler(Throwable $exception)"
in global/error.php (line 40)

**Comment by TimothyJones** [comment]
Nice catch. If you have time to make a PR, I'd definitely accept it.

**Comment by Sleepcap** [comment]
I'm not sure if there is more to change.
This is some very "basic"-level PHP-stuff, and I just solved this using google and some intuition.
The variable-names now no longer match their type, so is might be a good idea to change these as well.

It might be better if someone with a deeper understanding of PHP would check the code and solve this the "right" way.

**Comment by kestasjk** [comment]
Yep I think I saw this in the PHP 7.x changelog; this is the correct fix.

**Comment by jmo1121109** [comment]
fixed by @kestasjk
