### ISSUE TITLE
Captcha on registration page does not load

### ISSUE THREAD

**Issue by ryanproud** [kestasjk/webDiplomacy#310]
# Bug report
Doubtful this would be considered a bug, but I figured I'd follow the template anyway.  I'm trying to setup webDiplomacy on my own server and having issues with the captcha generation.  I'm not getting any errors and easycaptcha.php returns a 200 but no content.  I was also originally getting a content-type of text/html, but I added `header('Content-Type: image/jpeg');`, which fixed the Content-Type but did nothing to fix the actual issue.  These are the response headers I'm receiving.

```HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 28 Mar 2018 13:24:08 GMT
Content-Type: image/jpeg
Transfer-Encoding: chunked
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: imageToken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; path=/
```

I am using nginx, and just wondering if someone has come across this before and what the fix might have been.

## Expected behaviour

Captcha image displays.

## Actual behaviour

Broken image where captcha should be.

## Steps to reproduce

Load the registration page

**Comment by TimothyJones** [comment]
I think this is because some library (imagemagick?) is not installed. If you can confirm, I'll add this to the documentation.

**Comment by ryanproud** [comment]
@TimothyJones I was apparently missing GD2 (which I believe is in the documentation).  I guess what threw me was not getting any errors anywhere.

**Comment by alexintour** [comment]
Had the same problem. 
It was related to new PHP 7.1 version, where the class and function with the same name is deprecated.

solved by changing file php-captcha.inc.php line 105
from: function PhpCaptcha(
to: function __construct(
