### ISSUE TITLE
Mods should have ability to change game ranking type

### ISSUE THREAD

**Issue by PeregrineFlight** [kestasjk/webDiplomacy#314]
AdminCP lacks the ability to change game ranking types. It is occasionally requested to the mod team to make games unranked, etc. Such changes would currently need to be done directly in the database, which is not great, especially when there's no active dev. 

Probably would be a similar change to #173.

**Comment by jmo1121109** [comment]
I'm somewhat against updating this. The logic around how points that were bet in a game going from non unranked to unranked, especially if there were CD's, refunding everything except 5 to all people who aren't CD and figuring out what to do for replacements would get really messy really quick. I would also advise against doing it in the db. It's probably easier to cancel and start a new game at this point.

**Comment by PeregrineFlight** [comment]
Fair point. That might make it simply not worth the effort. It's also an incredibly rare occurance. I think I know of a mere two cases where this was done.
