### ISSUE TITLE
Colorblind features do not work on mobile display.

### ISSUE THREAD

**Issue by mkeCharlie** [kestasjk/webDiplomacy#324]
# Bug report

Enabling colorblindness features cause the in-game small map to not scale appropriately when viewing on a mobile device.

## Expected behaviour

Entire map is displayed.

## Actual behaviour

Top-left corner of map is displayed.

## Steps to reproduce

1. Enable colorblindness feature (any of the current 3).
2. Navigate to a game on a mobile device.

(Note: Reported on Android v 7.0 with Google Chrome v 66.0.3359.158)

**Comment by TimothyJones** [comment]
Thanks for the report, @mkeCharlie !

**Comment by cfhughes** [comment]
Pull request #328 is a fix for this.

**Comment by TimothyJones** [comment]
Fixed! Thanks!!
