### ISSUE TITLE
Please write all the rules on the website

### ISSUE THREAD

**Issue by JoaoLages** [kestasjk/webDiplomacy#335]
Thanks for making this project open source. But please try to at least write every rule of the game in the main page, instead of only showing a few. Or at least a link to the rules. We've suffered enough at the hands of enemies that win due to their knowledge of rules that are not clear.

**Comment by jmo1121109** [comment]
Are you talking about this page? http://www.webdiplomacy.net/intro.php

**Comment by TimothyJones** [comment]
I think that’s the page, yes.

I’ve thought that updating this would be an improvement for a long time- if someone wants to write the text and make the images, I’m happy to make the changes to the page.

**Comment by jmo1121109** [comment]
I'll see if any of the moderators have some time to work on that.

**Comment by TimothyJones** [comment]
Thanks Jmo. Also, @JoaoLages  if you have time to take a stab at an improved draft, I'd happily accept it.

As an aside, we both have TREC related repositories. Small world!

**Comment by sebastiaanspeck** [comment]
If no one has took it, I would like to take this issue.

**Comment by TimothyJones** [comment]
Please do!

**Comment by sebastiaanspeck** [comment]
I found this: https://github.com/kestasjk/webDiplomacy/blob/master/locales/English/rules.php

Is this not the rules page?

**Comment by TimothyJones** [comment]
Those are the site rules - for the game rules, you can find the rulebook online [here](https://www.wizards.com/avalonhill/rules/diplomacy.pdf).

You might also find [Edi's 5 min teaching guide](https://www.wizards.com/avalonhill/rules/diplomacy_fiveminguide.pdf) useful.

Please express the rules in your own words - for copyright reasons, we're unable to copy from the rulebook.

**Comment by sebastiaanspeck** [comment]
I have some time in a few hours. Thanks!

**Comment by PeregrineFlight** [comment]
Are we allowed to link the rulebook on the site?

If so, linking the [most recent rulebook](http://media.wizards.com/2015/downloads/ah/diplomacy_rules.pdf) (Same rules as the 2000 version, but with an updated and more readable layout) and the [DATC](http://web.inter.nl.net/users/L.B.Kruijswijk/) on the Dip rules page would be useful.

**Comment by jmo1121109** [comment]
Having just restyled a number of the intro pages and the FAQ there are more then a few links to the entire rulebook throughout the site and we have the DATC tests page that shows every possible rules scenario in clarity. What specifically is unclear with them currently?

**Comment by TimothyJones** [comment]
The hold moves are unclear (I think the site's version of the rules say
that a failed move is converted to a hold, which is not correct, and leads
people to incorrectly order support holds hoping for it to work).

T

**Comment by PeregrineFlight** [comment]
Broadly, the intro page Rules summary is obviously limited, and inherently incomplete. We occasionally encounter players who think webDip's summary is in fact the complete rules and get confused when they don't cover everything. 
Even just adding something at the bottom (or top?) of the intro page remarking on these rules being incomplete and linking to the full rulebook and DATC would be beneficial. 
Having them in the FAQ is nice, but also including them on the intro would be useful. Maybe I'll make a PR for it on Monday.

**Comment by kestasjk** [comment]
There is no document on the planet that can tell you the rules for Diplomacy. The closest you can get is the DATC, which catalogues and demonstrates all the possible anomalies and ambiguities that the rules simply don’t comment on (depending on which version of the rules you want to reference). He gives recommendations, which are what we stick to. I’m pretty sure in the FAQ or the intro I comment that these are the basics, read the rule book if you want to know more, and look at the DATC and DATC tests for the actual nitty gritty.

The intro I wrote was good enough for playdiplomacy to plaigiarise it along with everything else; I don’t think it’s that bad really. We don’t want to overwhelm people into thinking the game is really complicated and all about knowing the rule intricacies; it’s not about that, and it goes way deeper than most will care to dig.
