### ISSUE TITLE
Misspellings on the American Empire IV map

### ISSUE THREAD

**Issue by bmihai** [kestasjk/webDiplomacy#336]
On both the small and large "Fall of the American Empire IV" maps, the region Coahuila is spelled "Coahulia". The spelling is correct in dropdown menus, but not on the maps.

**Comment by TimothyJones** [comment]
Thanks for the report!

**Comment by bmihai** [comment]
No problem!
Another misspelling, again on both the small and large images of the same map is "Gulf of Fonesca", which should say "Gulf of Fonseca".

**Comment by TimothyJones** [comment]
Thanks for the fix @Espequair!
