### ISSUE TITLE
Additional Forum Post Sidebar Fields

### ISSUE THREAD

**Issue by PeregrineFlight** [kestasjk/webDiplomacy#356]
It would be useful to add several new fields to the profile sidebars of forum posts. Three I could see adding are:

**Current webDip Points:** This would be very helpful for setting up games on the forum. 

**Link to Main Site Profile:** For the obvious reasons of being able to tell who people are, better integration of the forum with main site, etc.

**Donator marker:** I'm sure I'm not the only one who finds the coloured donator names on the forum gaudy. Plus, the way it currently works gives the admin team extra work. Automating this would be much better. 

Of course, all three would require an easyway to correlate the forum and main site profiles, which I don't believe we currently have, given issue #286.

**Comment by jmo1121109** [comment]
Currently there is no way I can see with phpbb to do a calculated field, where the record draws from another. I asked on their support forum and got a non useful reply back, but I'm not sure my phrasing was amazing if someone else wants to take a stab at what we're asking. https://www.phpbb.com/community/viewtopic.php?f=641&t=2498311&p=15173926#p15173926

That said, this can also be accomplished by locating the code that changes different values you're discussing and adding an update sql statement there by joining the webdip userid on the phpbb_users table using the columns user_id and webdip_user_id in that table. Then you can link to phpbb_profile_fields_data and update based on the user_id column in there, which would give live updates on the new forum when the mods give donator status or when RR is recalculated. 

The fields I currently plan on trying to do this for are:
RR
Donator markers
Number of completed Games
and slightly different/less easy to do is adjusting the authentication module for creating a new user on the phpbb code side to a contact info field called webdip profile which would then show up under the ... on each person's posts on the new forum. 

This last one has been the hardest to do but I plan on getting the first three done in the next week or two. 

If anyone has any ideas on how to adjust phpbb custom fields to pull from a different data source though...that'd be highly welcome and much more ideal to do.

**Comment by PeregrineFlight** [comment]
I've had a new thought about part of this. We've talked in the past about giving people various recognitions—whether that's for donating, winning tournaments, contributing code, etc. Perhaps rather than having a "Donator markers" field, we could have a "Badges" field, which displays markers for all these different recognitions. I think this would create a more cohesive recognition system than what we're currently considering, by combining a bunch of different systems into one. 

If we do implement this 'Badges' field, a few things should definitely go into it. Donator badges are obvious. Tournament placement is better suited as a badge rather than an avatar change as well. One that could be added is retired mod/admin, as a recognition for people's past volunteering. Minor code contributions would also make more sense as a badge than an avatar change. 
Badges could include the site and code contributor awards as well, for consistency's sake. That way, only people with actual power—Owners, Admins, Mods, & Devs—would have avatars. 

Of course, this is a bit more work to implement, but I think it makes more sense to have a singular system of recognition rather than a motley group of structures acting together to do so.

**Comment by jmo1121109** [comment]
I wouldn't waste time thinking about site changes. Nobody with approval status will review code. It's not worth your time.

**Comment by TimothyJones** [comment]
I deleted a comment above suggesting that new work wouldn't be accepted.

I agree that a system of badges/ achievements would be a big improvement. I also agree that it is a substantial amount of work. Anyone with time willing to look in to it would be welcomed.

**Comment by jmo1121109** [comment]
I'm closing this one out, what we've found is that making custom adjustments to the phpbb3 forum causes significant issues during upgrades of the forum and during server moves. At this time we aren't considering making additional changes to the forum itself.
