### ISSUE TITLE
PHP 7.X =>Error triggered: assert(): Calling assert() with a string argument is deprecated

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#381]
Changing to PHP 7.X (X=1, 2 or 3) will throw an error on the "Games tab".
---
Error triggered: assert(): Calling assert() with a string argument is deprecated

Error: "assert(): Calling assert() with a string argument is deprecated"
Raised: "/usr/www/users/vdiplo/vDiplomacy/gamesearch/searchItems.php"
Line: "271"
---
As PHP 7.0 is really old now webhosters are removing support for this version. Might be a good time to work on these funktions to make them future-proof.

**Comment by MilesFM** [comment]
Yeah, the same thing happened to me. I don't think the code is going to be updated to the new versions for a while since the devs seem to be very busy.

**Comment by jmo1121109** [comment]
This was fixed by @kestasjk
