### ISSUE TITLE
Profile "Position" is incorrect

### ISSUE THREAD

**Issue by jmo1121109** [kestasjk/webDiplomacy#392]
On the profile page the "Position: 75 / 16456 (top 1%)" does not correctly reflect the number of users on the site. Either add a hover over explaining the number if it seems correct or fix the code to reflect the number of users on the site.

**Comment by shdant113** [comment]
I was always under the impression that that number referred to the number of people with >100 points. That is what is reflected for each user on the HOF page (https://www.webdiplomacy.net/halloffame.php). It could definitely be made more clear what that actually means.

**Comment by jmo1121109** [comment]
Yeah that seems to be the case and we've clarified now so I'm closing this out.
