### ISSUE TITLE
Error triggered: Column 'ip' cannot be null.

### ISSUE THREAD

**Issue by AlexKrimel** [kestasjk/webDiplomacy#394]
This was probably caused by a software bug. If these occur often try enabling error-logging via config.php, and report errors to the official devs for help.

**Comment by jmo1121109** [comment]
Hi there, 

If you're getting an active error logging into the site please email webdipmod@gmail.com with screenshots of the problem you're seeing and explain when you're seeing it. 

Thanks!

**Comment by jmo1121109** [comment]
@AlexKrimel any additional details you can provide to the mod email listed above?
