### ISSUE TITLE
Add confirmation when navigating away with unsaved orders

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#43]
To cut down on reports of misorders that are actually user error, we could add a confirmation when navigating away from the game board when a user has entered but not saved orders.

Currently it's possible to enter some draft orders, and then send a message (which causes a page reload, and wipes the draft orders).

**Comment by deltachemist** [comment]
I'd like to work on this. My first idea would be to use the onbeforeunload event. However Firefox does not fully support this event. Is there a better way to do so or would it be enough to have the confirmation (with custom text on most browsers and default text on Firefox)?

**Comment by yewang** [comment]
Seems like this issue should be closed as it has been resolved by this https://github.com/kestasjk/webDiplomacy/pull/229

**Comment by TimothyJones** [comment]
Good catch. I've opened #241 to deal with a bug in the fix.
