### ISSUE TITLE
User info page when registering needs several updates

### ISSUE THREAD

**Issue by Squigs44** [kestasjk/webDiplomacy#430]
While registering, the page that takes in user information has several issues. First, the options that it collects during registration do not save. Secondly, all the <hX> tags need to have the indent overwritten on all of the various registration step displays. Finally, the readonly "email" field shown with the registration token needs to be grayed out.

**Comment by jmo1121109** [comment]
Thanks for this report, verified, and planning on addressing these this weekend.

**Comment by jmo1121109** [comment]
Fixed
