### ISSUE TITLE
Reliability-page fails to load if there are NMRs in cancelled games

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#535]
If you open the reliability-breakdown on a user and some of the games are cancelled it fails to load the explanation-page.

**Comment by jmo1121109** [comment]
Do you have an example profile on vDip I can check this out on?

**Comment by Sleepcap** [comment]
Check userID=12023 on vDip

**Comment by jmo1121109** [comment]
Fixed.
