### ISSUE TITLE
Feature Request: Live-To-Postal

### ISSUE THREAD

**Issue by Restitution-Dip** [kestasjk/webDiplomacy#636]
An issue with live games is that they last an extremely indeterminate amount of time; a 5-minute turns game can last any given player between 45 minutes and 5 hours if it's played to completion.

A result of this seems to be that Live games end early, or have people drop out or throw the game when they get tired.

A way to fix this would be to have two additional settings available for live games: "transition after" and "next phase time".

Basically, after "transition after" amount of time passes, the next phase will complete, and then phase times will switch to the "next phase time" value.

I think this feature would significantly improve the live game experience, as I think a lot of players would enjoy playing the most interesting part of the game live, and then finishing off the stalemate lines and grinding over the next week or two.

If there's any interest in this feature, I could give a shot at implementing it (though I am by no means a web dev).

**Comment by jmo1121109** [comment]
This is on my eventual to-do list, if it is something you would like to tackle you're more than welcome. My time is somewhat limited right now, but I'd be around for questions.

**Comment by Restitution-Dip** [comment]
Cool, I think I will give it a shot.
