### ISSUE TITLE
The SQL-statements for updating the finishTime in the wD_(Backup-)Games tables take too long 

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#645]
The server just reponds with a timeout.

UPDATE `wD_Games` g SET `finishTime` = (SELECT MAX(n.timeSent) FROM `wD_Notices` n WHERE n.type = 'Game' AND n.linkID = g.id) WHERE (SELECT COUNT(1) FROM `wD_Notices` n1 WHERE n1.linkID = g.id AND `type` = 'Game') > 0 AND `gameOver` <> 'No';

UPDATE `wD_Backup_Games` g SET `finishTime` = (SELECT MAX(n.timeSent) FROM `wD_Notices` n WHERE n.type = 'Game' AND n.linkID = g.id) WHERE (SELECT COUNT(1) FROM `wD_Notices` n1 WHERE n1.linkID = g.id AND `type` = 'Game') > 0 AND `gameOver` <> 'No';

**Comment by jmo1121109** [comment]
fixed by https://github.com/kestasjk/webDiplomacy/pull/646
