### ISSUE TITLE
Error triggered: Field 'terrID' doesn't have a default value

### ISSUE THREAD

**Issue by yeager-j** [kestasjk/webDiplomacy#657]
# Bug report

Playing first game. The game got to the unit building step and crashed.

```
Error triggered: Field 'terrID' doesn't have a default value

Error: "Field 'terrID' doesn't have a default value"
Raised: "/objects/database.php"
Line: "377"
```

Using PHP5.6

**Comment by jmo1121109** [comment]
This is obviously delayed reply wise, sorry for that, I'm going to close this out. I haven't seen any crashed games on the server in a while. If you run into a game on the site please use webdipmod@gmail.com and one of the site mods will get your game up and running again.
