### ISSUE TITLE
Search for high point games

### ISSUE THREAD

**Issue by jmo1121109** [kestasjk/webDiplomacy#67]
Current search for new games does not allow you to see games that you do not have the points to join. This should be an option in the search paramaters in advance search to turn off so that people interested in a starting game can find it.

**Comment by TimothyJones** [comment]
Why not just remove the restriction that you can't see games you don't have the points for? If they said something like "you do not have the points to join this game", I think that would be fine.

**Comment by TimothyJones** [comment]
Thanks!
