### ISSUE TITLE
Search by Time Until Next Process Fix

### ISSUE THREAD

**Issue by jmo1121109** [kestasjk/webDiplomacy#68]
Searching for a game by Time Until Next Process Fix brings back paused games first. This is a bug, as it does not take the time until next phase of the paused game into account. The where clause needs to be altered on this query to correctly pull back paused games _only_ if they are actually in order of the time until next process.

**Comment by TimothyJones** [comment]
Hmm.... I *think* this is because paused games have their process time set to be whenever it would have been before they got paused. Maybe we just sort them at the end of the list like we do for the my game panel?
