### ISSUE TITLE
"Reliability Rating too low" when it is not

### ISSUE THREAD

**Issue by gimix2** [kestasjk/webDiplomacy#728]
# Bug report

In the mods inbox there are (at least) three messages from different users who are reporting problems accessing games they should be able to:

MytharGT reports not being able to access games with RR requirement >80% while their RR is 94%

Vinay Orekondy reports not being able to access any games with a RR requirement (they enclosed a screenshot where they're trying to access a 50% RR game). They had a RR as low as 31% but they didn't play for a long time so it reset correctly to 100% (now it is 84% because they did an unexcused NMR in a live game today)

Cool Sunday reported not being able to access games with RR 80% or more while their RR is 100%. Then they reported the problem partly fixed itself - they can now join 80% games, but not 100% ones.

The messages are all starred and have my tag
(gimix)

**Comment by kestasjk** [comment]
Thanks @gimix2 we've made changes to RR calcs so they get updated frequently using a new algorithm that should be more robust, can you let me know if this persists?
