### ISSUE TITLE
Adding Memcached Installation Notes

### ISSUE THREAD

**Issue by c-flaherty** [kestasjk/webDiplomacy#741]
When trying to update a local fork to the more recent commits on `master`, I ran into some hard-to-debug issues with the gamemaster detecting when games were ready to be processed. It turned out to be due to the fact that the more recent commits now use `memcached` to handle notifying the gamemaster when games should be processed early (via "game hints"): https://github.com/kestasjk/webDiplomacy/blob/master/objects/memcached.php.

I found it nontrivial to (1) realize that this was the issue, and (2) properly install and config `memcached`. I ended up following this guide and had success with it: https://access.redhat.com/solutions/1160613

We should update the guide to include documentation on how to setup `memcached` properly. Some info that should be added (that I don't really know): what's the minimum cache size (`CACHESIZE` in the `memcached` config file) needed? Is there a specific version of `memcached` needed?

**Comment by kestasjk** [comment]
Hey; yep you're right we do need to update this. We installed memcached for emergency performance issues, to be honest I'm not very familiar with it myself. I don't think you need a specific version, but people can get caught out by installing the similarly named incorrect version
