### ISSUE TITLE
Overhaul the FAQ/Help/getting started pages

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#79]
Some of the information in the FAQ, help and getting started pages is out of date or otherwise incorrect now. We should do a full pass over everything to make sure that it's correct.

This is a more general case of issue #72.

**Comment by jmo1121109** [comment]
Been through the content on most of these in a number of PR's the past couple weeks and gotten the incorrect content removed, and updated with new information. Closing this out.
