### ISSUE TITLE
Chat window sometimes cuts off messages

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#81]
From a member:

> When I fully expand the chat window to type, so that I can see more of what I’ve been typing, and then “send” the message, the message posted is cut off on the right hand side of the message display and unreadable.
> 
> This is also a minor  bug because users can open “Chat Archive” to read the message. (Not sure they all know that though).

http://webdiplomacy.net/board.php?gameID=152468 is an example of this issue. Looks like the message tab gets cut off for everyone when this happens, so it's a fairly important bug.

**Comment by jmo1121109** [comment]
Something to note with this bug is that if you highlight the text and move your mouse right it will allow you to read the entire message. There just isn't a visible scroll bar. This also happens on the forum when a long unbroken string is posted that goes off the page.

**Comment by jmo1121109** [comment]
This was fixed at some point in the last 4 years. Closing it out.
