### ISSUE TITLE
Quite a lot of new database entries, but no update.sql

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#83]
Just started to integrate the new webDip code in the vDip branch as I noticed you added some new columns and tables to the database, but there is no update.sql, so I have no clue how to add the tables.
I noticed the sql vor a version-change from 1.35 to 1.46, but the RR entries are missing.

**Comment by TimothyJones** [comment]
Ah, yes. Thanks for noticing that. I've asked Kestas for the queries he used to create the RR entries initially. I'll add them in ASAP.

**Comment by TimothyJones** [comment]
Should be fixed now! Please reopen if you have any futher issues. Thanks to Kestas for providing the missing SQL.
