### ISSUE TITLE
Bots not entering orders

### ISSUE THREAD

**Issue by tsouchlarakis** [kestasjk/webDiplomacy#867]
Example game: https://webdiplomacy.net/beta/?gameID=635255

The bots are not readying their orders, and as a result the game cannot progress past Spring '01.

**Comment by iz0717** [comment]
I am having the same issue. It started about 14 hours ago (May 25 2023 02:00 UTC) and has persisted. Tried clearing cookies, changing browsers, and opening new games. No luck.
