### ISSUE TITLE
Users incorrectly receive an NMR when they ready all holds without ever saving other orders

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#87]
If a users hasn't saved anything other than all holds, then they incorrectly get an NMR. This is because holds are the default orders, and if there never has been any other orders written, an NMR is incorrectly recorded.

The fix for this needs to contain a way to correct old records (possibly by parsing the order logs?)

**Comment by TimothyJones** [comment]
The cause was fixed in the above commit, and it was decided we'd wipe the NMR record clean rather than try to reconstruct the data from the order logs.

**Comment by Sleepcap** [comment]
On vDip we do count the phases played and missed, even if a country is in CD.
That way, as long as your country is in CD it's rating get's a hit each phase.
You could leave your country 4 phases in CD and receive only 2 NMRs (or even less) if it would stop counting after a CD.
