### ISSUE TITLE
St Petersburg (nc) has option to support itself to neighbouring provinces

### ISSUE THREAD

**Issue by CaptainMeme** [kestasjk/webDiplomacy#92]
When entering St Petersburg (nc) support move to [neighbouring province] from..., the option St Petersburg is given. If selected and saved, this brings up the error message:
!! Invalid order. Did you mean convoy instead of support move?

This may also happen with the south coast, but this hasn't been tested.

**Comment by TimothyJones** [comment]
I think I've seen this with the south coast, but I don't think I've seen it with other provinces. Interesting...

**Comment by diptobi1** [comment]
Hi, discovered this issue list by chance, as well as this particular problem.
I've written something about this bug on the dev-forum some time ago, that might help you:
http://forum.webdiplomacy.net/viewtopic.php?f=3&t=603

**Comment by TimothyJones** [comment]
Thanks diptobi! This is really helpful.

**Comment by TheMinisterOfWar** [comment]
This happens in Spain too.

**Comment by TimothyJones** [comment]
Fixed, thanks tobi.
