### ISSUE TITLE
Ancient Med has an L shape of colour belonging to the wrong province in Dal

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#96]
For some reason, Dalmatia has an L shape of Numidia's colour in it:

https://github.com/kestasjk/webDiplomacy/blob/master/variants/AncMed/resources/smallmap.png

This is fixed in vDiplomacy's repo - we can grab theirs.

**Comment by Sleepcap** [comment]
Made a pull request.
Added the ancient-icons we use on vDip too.
A friend of mind did these, so it's save to use them.
