### ISSUE TITLE
"Original press" mode for no press during retreats and disbands

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#99]
The original rules state that there should be no discussion during retreats and disbands. We should add this as a press mode.

I'm not sure what we should call this. "Original press"? "Tournament press"? "Hardcore press"?

**Comment by Sleepcap** [comment]
I would go with "Tournament press".
Sounds quite "official", and an explanation what this means would be needed anyway.

**Comment by TimothyJones** [comment]
The more I think about this, the more I think it should be called "rulebook press".
